name: Checking Tests

on:
  pull_request:
    branches:
      - develop
      - staging

jobs:
  test:
    name: Checking Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm install
      
      - name: Build App
        run: npm run build

      # Make sure this script name matches what's in your package.json
      # It might be 'test:component' instead of 'test-component'
      - name: Run Cypress component tests
        run: npm run test-component