name: Deploy To Render

on:
  push:
    branches: [main]

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install
         
      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"